# Site Settings
title: Unexciting Money Club
description: "Real-life finance for long-term thinkers. <br> No hype, no shortcutsâ€”just boring decisions."
url: "https://harieshmk.github.io/" 
baseurl: "" # Leave empty if your site is the main repository

# Author Settings (Helps with Trust/E-E-A-T)
author:
  name: "Hariesh Murugan"
  email: "itzhariesh@gmail.com"
  instagram: "unexciting_money_club"

# Build Settings
permalink: /blog/:title/  # Simplified: shorter URLs usually rank better
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag # I highly recommend adding this one!

# Future-proofing
show_downloads: false
