title: Unexciting Money Club
description: Real-life finance. No hype. No shortcuts.

show_downloads: false
github:
  is_project_page: false
  is_user_page: false

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
