# Site Settings
title: Unexciting Money Club
description: "Real-life finance for long-term thinkers. No hype, no shortcutsâ€”just boring decisions."
url: "https://harieshmk.github.io/" 
baseurl: "" 

# Author Settings
author:
  name: "Hariesh Murugan"
  email: "itzhariesh@gmail.com"
  instagram: "unexciting_money_club"

# Build Settings
permalink: /blog/:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
